name: "📦 Package Addon"
description: "Downloads and prepares an addon via pkg-prebuilds"

inputs:
  arch:
    required: true
    description: Either 'amd64' or 'arm64'

runs:
  using: "composite"
  steps:
      - name: 📦 Download Build
        uses: actions/download-artifact@v8
        with:
          name: addon-${{ inputs.arch }}
          path: build/MinSizeRel

      - name: 🛠️ Prepare Prebuilds
        shell: bash
        run: |
          pnpm pkg-prebuilds-copy --baseDir build/MinSizeRel --source venmic-addon.node --name=venmic-addon --strip --napi_version=7 --arch=${{ inputs.arch == 'amd64' && 'x64' || 'arm64' }}
