on:
  push:
  pull_request:
  workflow_dispatch:

name: 🧪 Build & Test

jobs:
  build-addon:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v7

      - name: 🧪 Build & Test Addon
        uses: ./.github/actions/build
        with:
          command: pnpm install --ignore-scripts && pnpm run configure && pnpm run build && pnpm run test

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: addon
          path: build

  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v7

      - name: 🏗️ Build Server
        uses: ./.github/actions/build
        with:
          command: cmake -B build && cmake --build build

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: server
          path: build
